{
 "title": "IOTA Validator",
 "tags": [
  "IOTA",
  "METRICS"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Network state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest executed checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_executed_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total number transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_transaction_certificates", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Checkpoint time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / rate(last_executed_checkpoint[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction per seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(total_transaction_effects[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates per second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(num_shared_obj_tx[1m])", "legendFormat": "__auto" }
   ]
  },
  { "title": "Node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Node Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "checkpoint_exec_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voiting power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_voting_right / 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Checkpoint",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "highest_synced_checkpoint", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime / 60 /60 ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Checkpoint SYNC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_executed_checkpoint / highest_synced_checkpoint * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certificates SYNC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(consensus_threshold_clock_round/consensus_highest_accepted_round) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_executed_checkpoint - highest_synced_checkpoint",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iota_network_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total transaction order",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_transaction_orders", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Certificates processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_last_committed_leader_round",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delay execution checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "checkpoint_exec_latency_us", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sync TPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "checkpoint_exec_sync_tps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inbound Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "iota_inbound_request_latency_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onbound Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "iota_outbound_request_latency_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Uptime CT",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node-metrics\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-metrics\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Validator System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"node-metrics\"}[1m])) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"node-metrics\"} / (node_memory_MemTotal_bytes{job=\"node-metrics\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{job=\"node-metrics\"} / node_memory_SwapTotal_bytes{job=\"node-metrics\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - (node_filesystem_free_bytes{job=\"node-metrics\", device=\"/dev/sda2\"} *100 / node_filesystem_size_bytes{job=\"node-metrics\",device=\"/dev/sda2\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "100 - (node_filesystem_free_bytes{job=\"node-metrics\",device=\"/dev/sda1\"} *100 / node_filesystem_size_bytes{job=\"node-metrics\",device=\"/dev/sda1\"})",
     "legendFormat": "Boot"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {job=\"node-metrics\",fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{job=\"node-metrics\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node-metrics',fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node-metrics\"}"
    }
   ]
  },
  {
   "title": "Validator Avg. System Load",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-metrics\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{job=\"node-metrics\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{job=\"node-metrics\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU usage, disk I/O operations per second take time（%）",
   "type": "timeseries",
   "description": "node_disk_io_time_seconds_total：\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value.（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is, the percentage of time that the disk spends on I/O operations in 1 second.",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"node-metrics\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"node-metrics\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_% of I/O operations per second"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"node-metrics\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "Disk read and write rate（IOPS）",
   "type": "timeseries",
   "description": "Reads completed: Reads per second per disk partition\n\nWrites completed: Number of writes per second per disk partition\n\nIO now Number of input/output requests being processed per disk partition per second",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk read and write capacity",
   "type": "timeseries",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "timeseries",
   "description": "Read time ms Number of seconds per disk partition read operation\n\nWrite time ms Number of seconds spent per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\n IO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_write"
    },
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{job=\"node-metrics\"}[1m])",
     "legendFormat": "{{device}}_weighted"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-metrics\",device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in received"
    },
    {
     "expr": "-(irate(node_network_transmit_bytes_total{job=\"node-metrics\",device!~'tap.*'}[5m])*8)",
     "legendFormat": "{{device}}_out sent"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "timeseries",
   "description": "CurrEstab - TCP connections with current state ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from CLOSED state to SYN-SENT state (within 1 minute)\n\nPassiveOpens - Directly from LISTEN state The average number of TCP connections to SYN-RCVD state (within 1 minute)\n\nTCP_all oc - the number of TCP sockets allocated (established, applied to sk_buff)\n\nTCP_inuse - in use (listening The number of TCP sockets \n\nTCP_tw - the number of TCP connections waiting to be closed",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"node-metrics\"}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{job=\"node-metrics\"}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{job=\"node-metrics\"}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"node-metrics\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_TCP_alloc{job=\"node-metrics\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{job=\"node-metrics\"}",
     "legendFormat": "TCP_inuse"
    }
   ]
  }
 ]
}